### ISSUE TITLE
The vault contract should be mapped with L2 child contract

### ISSUE THREAD

**Issue by crazybae** [GoSquidGame/GoSquidGame.github.io#4]
Step 1 for deposit
vault contract:  approve a token to bridgePredicate contract --> success
    - owerOf function of the vault contract works very nicely!

Step 2 for deposit
rootchainManager contract (matic):  deposit the token and mint a new corresponding token in L2 --> FAILURE (see the error message below)

the contract rootchainManager does not work without mappint between L1 and L2 (see depositFor function in https://goerli.etherscan.io/address/0x0d2ae21bf7e72f646ef8e1f2aa92edbd13588691#code )

Make a child nft contract in L2 and register a mapping between VAULT contract (not original nft contract) in L1 and the child nft contract in L2.   See  https://mapper.matic.today/map/

error message

Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"name":"ProviderError","code":3,"_isProviderError":true,"data":"0x08c379a000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000022526f6f74436861696e4d616e616765723a20544f4b454e5f4e4f545f4d4150504544000000000000000000000000000000000000000000000000000000000000"}, method="estimateGas", transaction={"from":"0x4278827E51e1453af40ad3F454AE5b556823217c","to":"0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74","data":"0xe3dec8fb0000000000000000000000004278827e51e1453af40ad3f454ae5b556823217c000000000000000000000000bf6cc26c2ca10b59aa68fca6edac0773ce306c9700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c","accessList":null}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.5.0)
    at Logger.makeError (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/logger/src.ts/index.ts:225:28)
    at Logger.throwError (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/logger/src.ts/index.ts:237:20)
    at checkError (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:80:16)
    at EthersProviderWrapper.<anonymous> (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:562:20)
    at step (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/kbae/src/GoSquidGame.github.io/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: ProviderError: execution reverted: RootChainManager: TOKEN_NOT_MAPPED
      at HttpProvider.request (/home/kbae/src/GoSquidGame.github.io/node_modules/hardhat/src/internal/core/providers/http.ts:49:19)
      at HDWalletProvider.request (/home/kbae/src/GoSquidGame.github.io/node_modules/hardhat/src/internal/core/providers/accounts.ts:168:34)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at EthersProviderWrapper.send (/home/kbae/src/GoSquidGame.github.io/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20),
  method: 'estimateGas',
  transaction: {
    from: '0x4278827E51e1453af40ad3F454AE5b556823217c',
    to: '0xBbD7cBFA79faee899Eaf900F13C9065bF03B1A74',
    data: '0xe3dec8fb0000000000000000000000004278827e51e1453af40ad3f454ae5b556823217c000000000000000000000000bf6cc26c2ca10b59aa68fca6edac0773ce306c9700000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000002c',
    accessList: null
  }
}

**Comment by crazybae** [comment]
the following counterparty NFT contract in L2 will be mapped with the vault contract in L1:
0x2E39443148785c9be0d7343799Ed48672381e056  (matic mumbai)
